### ISSUE TITLE
won't install on windows10/python3.5

### ISSUE THREAD

**Issue by mentat51** [harvimt/pylib7zip#2]
python setup.py install give me : 
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    import lib7zip
  File "C:\usr\home\dev\python\pylib7zip-master\lib7zip__init__.py", line 94, in <module>
    C = ffi.dlopen(None)
  File "C:\usr\bin\Python35\lib\site-packages\cffi\api.py", line 127, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "C:\usr\bin\Python35\lib\site-packages\cffi\api.py", line 622, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "C:\usr\bin\Python35\lib\site-packages\cffi\api.py", line 610, in _load_backend_lib
    raise OSError("library not found: %r" % (name,))
OSError: library not found: 'c'

No idea how to fix this.

Thanks if you have some time to give me a starting point.

**Comment by harvimt** [comment]
Duh. It doesn't work at all.

Be patient or code something yourself.

**Comment by harvimt** [comment]
I am working on this again after throwing this slapdash mostly non-working version up years ago. (this version might work on 64bit linux with python 2.7 for some value of work)
